# Site settings
title: "Welcome to my blog"
description: > 
  For Eureka

author: Minji Kim
email: minji99@cogaplex.com
twitter_username: None
github_username: meanz1

baseurl: " " # the subpath of your site, e.g. /blog
url: "https://meanz1.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id: meanz1-github-io.disqus.com

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

